root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ."

bin = "./tmp/main"

# 80番ポートで待ち受ける
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", ".git"]
include_dir = []
# 監視するファイルを明示的に指定
watch_dir = ["."]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlinks = true
log = "air.log"
delay = 0 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500
# Docker環境でのファイル変更検知のためのポーリング設定
poll = true
poll_interval = 100 # ms
# macOS Dockerでのファイル監視改善
rerun = true
rerun_delay = 100

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true