linters-settings:
  misspell:
    locale: US
  gocyclo:
    min-complexity: 30

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace