version: "3.9"
services:
  app:
    # コンテナ名
    image: gotodo
    # ビルドコンテナ
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - target=dev
    environment:
      - TODO_ENV=dev
      - PORT=8080
      - TODO_DB_HOST=todo-db
      - TODO_DB_PORT=3306
      - TODO_DB_USER=todo
      - TODO_DB_PASSWORD=todo
      - TODO_DB_NAME=todo
    # ホストマシンのディレクトリをマウント
    volumes:
      - .:/app
    ports:
      - "18080:8080"
    depends_on:
      - todo-db
    networks:
      - todo-network
    
  todo-db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: todo-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
      - MYSQL_DATABASE=todo
    volumes:
      - todo-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
    networks:
      - todo-network

volumes:
  todo-db-data:

networks:
  todo-network:
    driver: bridge