name: golangci

on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci.yml'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create dummy cert files for CI
        run: |
          mkdir -p auth/cert
          echo "-----BEGIN RSA PRIVATE KEY-----" > auth/cert/secret.pem
          echo "dummy private key content" >> auth/cert/secret.pem
          echo "-----END RSA PRIVATE KEY-----" >> auth/cert/secret.pem
          echo "-----BEGIN PUBLIC KEY-----" > auth/cert/public.pem
          echo "dummy public key content" >> auth/cert/public.pem
          echo "-----END PUBLIC KEY-----" >> auth/cert/public.pem
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Download dependencies
        run: go mod download
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: "./..."