name: golangci

on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Download dependencies
        run: go mod download
      
      - name: Create dummy cert files for CI
        run: |
          mkdir -p auth/cert
          echo "-----BEGIN RSA PRIVATE KEY-----" > auth/cert/secret.pem
          echo "dummy private key content" >> auth/cert/secret.pem
          echo "-----END RSA PRIVATE KEY-----" >> auth/cert/secret.pem
          echo "-----BEGIN PUBLIC KEY-----" > auth/cert/public.pem
          echo "dummy public key content" >> auth/cert/public.pem
          echo "-----END PUBLIC KEY-----" >> auth/cert/public.pem
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: "./..."
          only-new-issues: true