name: golangci

on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci.yml'

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: "./..."